apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - git:
      ref: v2.9.3
      url: https://github.com/argoproj/argo-cd
    includePaths:
    - manifests/install.yaml
    newRootPath: manifests
    path: .
  path: config/upstream
kind: Config
minimumRequiredVersion: ""
